<?php

namespace App\Filament\Resources\LogbookProfiles\Schemas;

use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Schema;

class LogbookProfileInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextEntry::make('logbook_id')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('chasisNumber')
                    ->placeholder('-'),
                TextEntry::make('regNumber')
                    ->placeholder('-'),
                TextEntry::make('CardCode')
                    ->placeholder('-'),
                TextEntry::make('CardName')
                    ->placeholder('-'),
                TextEntry::make('CustomerName')
                    ->placeholder('-'),
                TextEntry::make('DocNum')
                    ->placeholder('-'),
                TextEntry::make('Location')
                    ->placeholder('-'),
                TextEntry::make('PinNo')
                    ->placeholder('-'),
                TextEntry::make('IDNo')
                    ->placeholder('-'),
                TextEntry::make('TransFerDate')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('DocDate')
                    ->placeholder('-'),
                TextEntry::make('NumAtCard')
                    ->placeholder('-'),
                TextEntry::make('tel')
                    ->placeholder('-'),
                TextEntry::make('LogBookFee')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('U_ProdLine')
                    ->placeholder('-'),
                TextEntry::make('EngineNumber')
                    ->placeholder('-'),
                TextEntry::make('groupCode')
                    ->placeholder('-'),
                TextEntry::make('groupName')
                    ->placeholder('-'),
                TextEntry::make('createdOn')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('createdBy')
                    ->placeholder('-'),
                TextEntry::make('editedOn')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('editedBy')
                    ->placeholder('-'),
                TextEntry::make('created_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('updated_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('status')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('isAllocated')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('allocatedBy')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('allocatedOn')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('isAvailable')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('isReturned')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('returnedBy')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('returnedOn')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('packingListCreatedOn')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('packingListCreatedBy')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('allocationsCreatedOn')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('allocationsCreatedBy')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('pendingRequestsCreatedOn')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('pendingRequestsCreatedBy')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('requestsCreatedOn')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('requestsCreatedBy')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('pendingAcceptanceCreatedOn')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('pendingAcceptanceCreatedBy')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('acceptanceCreatedOn')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('acceptanceCreatedBy')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('issuesCreatedOn')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('issuesCreatedBy')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('dispatchCreatedOn')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('dispatchCreatedBy')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('dispatchedDate')
                    ->placeholder('-'),
                TextEntry::make('dispatchedBy')
                    ->placeholder('-'),
                TextEntry::make('dispatchedTo')
                    ->placeholder('-'),
                TextEntry::make('dispatchedYear')
                    ->placeholder('-'),
                TextEntry::make('applicationNumber')
                    ->placeholder('-'),
                TextEntry::make('dealer_location')
                    ->placeholder('-'),
                TextEntry::make('data_source')
                    ->placeholder('-'),
                TextEntry::make('ItemCode')
                    ->placeholder('-'),
            ]);
    }
}
